[tool.poetry]
name = "natual-language-ai"
version = "0.1.0"
description = ""
authors = ["ohr486 <ohr486@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
